print('='*8,'Dissecando uma String','='*8)
a = input('Digite algo qualquer:')
print('O tipo primitivo desse valor e {}'.format(type(a)))
print('O valor e alphanumerico? {}.'.format(a.isalnum()))
print('O valor e alfabetico? {}.'.format(a.isalpha()))
print('O valor e um numero? {}.'.format(a.isnumeric()))
print('O valor esta todo em minusculo? {}.'.format(a.islower()))
print('O valor esta capitalizado? {}.'.format(a.istitle()))
print('O valor so possui espacos? {}.'.format(a.isspace()))
