print('='*8,'Tuplas com Times de Futebol','='*8)
cf = ('Palmeiras', 'Santos', 'Vasco da Gama', 'Grêmio', 'Flamengo', 'Corinthians', 'Internacional', 'Cruzeiro', 'São Paulo', 'Atlético Mineiro', 'Botafogo', 'Fluminense', 'Coritiba', 'Bahia', 'Goiás', 'Guarani', 'Sport', 'Portuguesa', 'Atlético Paranaense', 'Vitória')
print('De acordo com os dados do Campeonato Brasileiro de Futebol temos que:')
print('-=' * 40)
print(f'A lista dos 20 primeiros colocados é: {cf}.')
print('-=' * 40)
print(f'Os cinco primeiros colocados são: {cf[:5]}.')
print('-=' * 40)
print(f'Os quatro últimos colocados são: {cf[-4:]}.')
print('-=' * 40)
print(f'A lista dos times em ordem alfabética fica: {sorted(cf)}.')
print('-=' * 40)
print(f'E o time Chapecoense não está entre os vinte primeiros da CBF.')
print('-=' * 40)
